source "https://rubygems.org"
ruby ">= 3.2.0"
gem "rails", "~> 8.1.4"
gem "pg", "~> 1.6"
gem "puma", ">= 6.0"
gem "bcrypt", "~> 3.1"
gem "sidekiq", "~> 7.3"
gem "redis", "~> 5.0"
gem "pundit", "~> 2.5"
gem "rack-cors"
gem "rack-attack"
gem "roo", "~> 2.10"
gem "csv"
gem "aws-sdk-s3", require: false
group :development, :test do
  gem "rspec-rails", "~> 8.0"
  gem "factory_bot_rails"
end
