"use client";
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api} from '@/lib/api';
import {toast} from 'sonner';
type TeamData={members:{id:number;role:string;user:{name:string;email:string}}[];invitations:{id:number;email:string;role:string}[];member_limit:number};
export function Team({businessId}:{businessId:number}){
 const client=useQueryClient(),[link,setLink]=useState(''),[busy,setBusy]=useState(false);
 const team=useQuery({queryKey:['team',businessId],queryFn:()=>api<TeamData>('team_members',{},businessId)});
 async function remove(path:string){if(!window.confirm('Remove this access to your store?'))return;try{await api(path,{method:'DELETE'},businessId);await client.invalidateQueries({queryKey:['team',businessId]});toast.success('Access removed')}catch(e){toast.error((e as Error).message)}}
 return <section className="settings"><h2>Your team</h2><p className="muted">Staff add products and record stock changes. Managers also edit products and view reports. Admins manage your team. Everyone has their own login.</p>{team.error&&<p role="alert">{team.error.message}</p>}{team.data&&<><p>{team.data.data.members.length+team.data.data.invitations.length} / {team.data.data.member_limit} users · includes owner and pending invitations</p>{team.data.data.members.map(m=><div className="plan-row" key={m.id}><span><strong>{m.user.name}</strong><br/>{m.user.email} · {m.role}</span>{m.role!=='owner'&&<button type="button" className="button subtle" onClick={()=>remove(`team_members/${m.id}`)}>Remove</button>}</div>)}{team.data.data.invitations.map(i=><div className="plan-row" key={i.id}><span>{i.email} · invitation pending</span><button type="button" className="button subtle" onClick={()=>remove(`team_invitations/${i.id}`)}>Revoke</button></div>)}</>}
 <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setLink('');try{const r=await api<{token:string}>('team_invitations',{method:'POST',body:JSON.stringify({invitation:{email:f.get('email'),role:f.get('role')}})},businessId);setLink(`${location.origin}/join#token=${encodeURIComponent(r.data.token)}`);await client.invalidateQueries({queryKey:['team',businessId]})}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}}><label>Employee email<input name="email" type="email" required/></label><label>Role<select name="role" defaultValue="staff"><option value="staff">Staff</option><option value="manager">Manager</option><option value="admin">Admin</option></select></label><button className="button primary full" disabled={busy||!!team.data&&team.data.data.members.length+team.data.data.invitations.length>=team.data.data.member_limit}>{busy?'Creating invitation…':'Create invitation'}</button></form>{link&&<div className="error-box"><p>Share this link with your employee. Valid for 7 days, for their invited email only. No email was sent automatically.</p><input aria-label="Invitation link" readOnly value={link} onFocus={e=>e.target.select()}/><button type="button" className="button subtle" onClick={async()=>{try{await navigator.clipboard.writeText(link);toast.success('Copied')}catch{toast.error('Select and copy the link manually')}}}>Copy link</button></div>}</section>
}
