export const checkoutCopy = {
  en: {
    title: "A smoother checkout.",
    subtitle: "Scan, add, bill. Keep the queue moving.",
    checkout: "Checkout",
    history: "Bills",
    search: "Search name, SKU or barcode",
    scan: "Scan barcode",
    enter: "Scan or enter barcode",
    find: "Add to cart",
    cart: "Current bill",
    empty: "Ready for your first scan.",
    emptyHelp: "Scan a barcode or tap a product to start a bill.",
    quantity: "Quantity",
    price: "Price",
    remove: "Remove",
    subtotal: "Subtotal",
    discount: "Bill discount",
    total: "Total",
    customer: "Customer name (optional)",
    phone: "Phone (optional)",
    payment: "Payment received by",
    cash: "Cash",
    upi: "UPI",
    card: "Card",
    other: "Other",
    complete: "Complete sale & create bill",
    saving: "Saving your bill…",
    saved: "Bill saved. Stock updated.",
    review: "Review before confirming",
    confirm: "Confirm sale",
    cancel: "Back to cart",
    confirmHelp:
      "This records payment received and deducts stock. It does not charge a card or collect UPI payment.",
    newSale: "New sale",
    print: "Print / Save PDF",
    share: "Share bill",
    receipt: "Sales receipt",
    bill: "Bill",
    cashier: "Cashier",
    date: "Date",
    noTax: "Simple sales receipt · tax calculation is not configured",
    allBills: "All store bills",
    ownBills: "Your bills",
    noBills: "Your first bill starts here.",
    status: "Status",
    completed: "Completed",
    partially_returned: "Partially returned",
    returned: "Returned",
    returns: "Returns",
    returnAction: "Return items",
    returnQty: "Return quantity",
    reason: "Reason for return",
    returnConfirm: "Confirm return & restock",
    returnHelp:
      "Only return resellable items here. Refund payment separately; this records the amount and restores stock.",
    refund: "Refund recorded",
    remaining: "Available",
    missing: "New barcode. Add this product to your shelves.",
    addProduct: "Add new product",
    clear: "Clear cart",
    clearConfirm: "Clear this cart? No stock has been changed.",
    loading: "Loading…",
    retry: "Try again",
    previous: "Previous",
    next: "Next",
    pending:
      "Checkout response uncertain. Retry the same bill to avoid duplicate sales.",
    staffPrice:
      "Staff use saved prices. Ask a manager for discounts or price changes.",
    copied: "Bill copied",
    returnedBy: "Processed by",
    language: "Checkout language",
    paid: "Payment recorded",
    items: "items",
    note: "Return note",
    invalid: "Check quantities and prices before continuing.",
    maxStock: "Not enough available stock",
    add: "Add",
    close: "Close",
    billSearch: "Search bill number or customer",
    refundTotal: "Total returned",
    netTotal: "Net after returns",
  },
  hi: {
    title: "अब बिल बनाना आसान।",
    subtitle: "स्कैन करें, सामान जोड़ें और बिल बनाएं।",
    checkout: "बिल बनाएं",
    history: "बिल इतिहास",
    search: "नाम, SKU या बारकोड खोजें",
    scan: "बारकोड स्कैन करें",
    enter: "स्कैन करें या बारकोड लिखें",
    find: "कार्ट में जोड़ें",
    cart: "वर्तमान बिल",
    empty: "पहला सामान स्कैन करें।",
    emptyHelp: "बारकोड स्कैन करें या सामान चुनकर बिल शुरू करें।",
    quantity: "मात्रा",
    price: "कीमत",
    remove: "हटाएं",
    subtotal: "उप-कुल",
    discount: "बिल पर छूट",
    total: "कुल",
    customer: "ग्राहक का नाम (वैकल्पिक)",
    phone: "फोन (वैकल्पिक)",
    payment: "भुगतान का माध्यम",
    cash: "नकद",
    upi: "यूपीआई",
    card: "कार्ड",
    other: "अन्य",
    complete: "बिक्री पूरी करें और बिल बनाएं",
    saving: "बिल सहेजा जा रहा है…",
    saved: "बिल सहेजा गया। स्टॉक अपडेट हो गया।",
    review: "पुष्टि से पहले जांचें",
    confirm: "बिक्री की पुष्टि करें",
    cancel: "कार्ट पर वापस जाएं",
    confirmHelp:
      "इससे प्राप्त भुगतान दर्ज होगा और स्टॉक घटेगा। यह कार्ड या UPI से पैसे नहीं काटता।",
    newSale: "नई बिक्री",
    print: "प्रिंट / PDF सेव करें",
    share: "बिल साझा करें",
    receipt: "बिक्री रसीद",
    bill: "बिल",
    cashier: "कर्मचारी",
    date: "तारीख",
    noTax: "साधारण बिक्री रसीद · टैक्स गणना अभी उपलब्ध नहीं है",
    allBills: "दुकान के सभी बिल",
    ownBills: "आपके बिल",
    noBills: "आपका पहला बिल यहीं बनेगा।",
    status: "स्थिति",
    completed: "पूरा हुआ",
    partially_returned: "कुछ सामान वापस",
    returned: "वापस किया गया",
    returns: "वापसी",
    returnAction: "सामान वापस लें",
    returnQty: "वापसी की मात्रा",
    reason: "वापसी का कारण",
    returnConfirm: "वापसी दर्ज करें और स्टॉक जोड़ें",
    returnHelp:
      "यहां केवल दोबारा बेचने योग्य सामान वापस लें। पैसे अलग से लौटाएं; यहां रकम दर्ज होगी और स्टॉक बढ़ेगा।",
    refund: "वापसी की रकम दर्ज हुई",
    remaining: "उपलब्ध",
    missing: "नया बारकोड। पहले यह सामान जोड़ें।",
    addProduct: "नया सामान जोड़ें",
    clear: "कार्ट खाली करें",
    clearConfirm: "कार्ट खाली करें? स्टॉक अभी नहीं बदला है।",
    loading: "लोड हो रहा है…",
    retry: "फिर कोशिश करें",
    previous: "पिछला",
    next: "अगला",
    pending:
      "बिक्री का जवाब नहीं मिला। दोहरा बिल रोकने के लिए इसी बिल को फिर भेजें।",
    staffPrice:
      "कर्मचारी तय कीमत पर बेच सकते हैं। छूट या कीमत बदलने के लिए मैनेजर से कहें।",
    copied: "बिल कॉपी किया गया",
    returnedBy: "दर्ज करने वाला",
    language: "बिल की भाषा",
    paid: "भुगतान दर्ज",
    items: "सामान",
    note: "वापसी विवरण",
    invalid: "आगे बढ़ने से पहले मात्रा और कीमत जांचें।",
    maxStock: "पर्याप्त स्टॉक नहीं है",
    add: "जोड़ें",
    close: "बंद करें",
    billSearch: "बिल नंबर या ग्राहक खोजें",
    refundTotal: "कुल वापसी",
    netTotal: "वापसी के बाद कुल",
  },
} as const;
export type CheckoutLanguage = keyof typeof checkoutCopy;
